version: '2.1'
orbs:
  win: circleci/windows@4.1.1
jobs:
  build:
    working_directory: ~/project
    executor:
      name: win/default
    steps:
      - checkout
      # - restore_cache:
      #     key: choco-downloads-{{ checksum "pteid-mw-pt/windows/packages.config" }}
      - restore_cache:
          key: external-libs-downloads-{{ checksum "pteid-mw-pt/windows/config_external_libs.ps1" }}
      - run: '.\pteid-mw-pt/windows/config_external_libs.ps1'
      - save_cache:
          paths:
            - pteid-mw-pt/windows/external_libs
          key: external-libs-downloads-{{ checksum "pteid-mw-pt/windows/config_external_libs.ps1" }}
      # - run: 'choco config set --name "cacheLocation" --value "pteid-mw-pt/windows\chocoTemp"'
      # - run: 'choco install pteid-mw-pt/windows\packages.config --no-progress --side-by-side'
      - save_cache:
          paths:
            - pteid-mw-pt/windows\chocoTemp
          key: choco-downloads-{{ checksum "pteid-mw-pt/windows/packages.config" }}
workflows:
  my-workflow:
    jobs:
      - build

